# Generated by Django 2.2.5 on 2020-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_preview',
            field=models.ImageField(blank=True, null=True, upload_to='post-preview/%Y/%m/%d', verbose_name='عکس پیش نمایش پست'),
        ),
    ]
